### PR TITLE
Remove node_modules and fix warning for add-path

### PR DESCRIPTION
**Pull request by ghost**
node_modules should not be checked in. This PR removes the directory and also adds a .gitignore. This should solve the warning that appears since the deprecation of "add-path":

> The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Depending on @actions/core@^1.2.6 is correct, but there was a version of @actions/core in the checked in node_modules whose addPath function was:

```javascript
function addPath(inputPath) {
    command_1.issueCommand('add-path', {}, inputPath);
    process.env['PATH'] = `${inputPath}${path.delimiter}${process.env['PATH']}`;
}
```

### CODE REVIEW

**Comment by Warchant** [comment]
In normal projects, yes, you should exclude node_modules. But, unfortunately, if gh action is written in JS, it must have all the code present in repo, and CI suggests that (it fails with `Error: Cannot find module '@actions/core'`)

**Comment by ghost** [comment]
I'll admit I'm kinda new to github actions, but the version of @actions/core that exists in the checked in node_modules is not the one that package.json depends on, and that causes deprecation warnings when running this action.

I've been checking how other packages solves this and it seems like a dist folder containing the built artifact is to be checked in instead of node_modules. https://github.com/actions/javascript-action also suggests this. I've done that on my branch and I've confirmed that it works on our internal workflow. I would update the PR if I could, but maybe I can't because it's closed?

https://github.com/samuelandersson-axis/setup-sonar-scanner/commit/ac133fee3a07a7cb706923c3385e064f5c1c8d34

**Comment by Warchant** [comment]
@samuelandersson-axis reopened so you can try to fix CI

**Comment by ghost** [comment]
So the CI job has run, and sonar-scanner seems to have worked, but I'm not sure why it's saying 

`ERROR: You're not authorized to run analysis. Please contact the project administrator.`

Does it fetch credentials from MY repository? In that case it will always fail, because I don't have required secrets. At least it's not failing on @actions/core.

**Comment by Warchant** [comment]
I think this is because by-default CI of this repo is using my SONAR_TOKEN, which is not available on your fork repo. 
Lets try to merge this to master and see if it passes.

**Comment by Warchant** [comment]
Yep, it worked. Thanks for contribution!

**Comment by ghost** [comment]
Thanks for merging! Have a good day!

**Pull request merged**
